export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';

export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
export const SEARCH_CHARACTER_SUCCESS = 'SEARCH_CHARACTER_SUCCESS';
export const SEARCH_CHARACTER_ERROR = 'SEARCH_CHARACTER_ERROR';

export const GET_PLANET = 'GET_PLANET';
export const GET_PLANET_SUCCESS = 'GET_PLANET_SUCCESS';
export const GET_PLANET_ERROR = 'GET_PLANET_ERROR';

export const GET_SPECIE = 'GET_SPECIE';
export const GET_SPECIE_SUCCESS = 'GET_SPECIE_SUCCESS';
export const GET_SPECIE_ERROR = 'GET_SPECIE_ERROR';

export const GET_STARSHIP = 'GET_STARSHIP';
export const GET_STARSHIP_SUCCESS = 'GET_STARSHIP_SUCCESS';
export const GET_STARSHIP_ERROR = 'GET_STARSHIP_ERROR';

// be careful with this one son there's a Promise.all()
export const GET_STARSHIPS = 'GET_STARSHIPS';
export const GET_STARSHIPS_SUCCESS = 'GET_STARSHIPS_SUCCESS';
export const GET_STARSHIPS_ERROR = 'GET_STARSHIPS_ERROR';
