export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_ERROR = 'GET_CHARACTERS_ERROR';

export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';

export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
export const SEARCH_CHARACTER_SUCCESS = 'SEARCH_CHARACTER_SUCCESS';
export const SEARCH_CHARACTER_ERROR = 'SEARCH_CHARACTER_ERROR';

export const GET_ADDITIONNAL_INFOS = 'GET_ADDITIONNAL_INFOS';
export const GET_ADDITIONNAL_INFOS_SUCCESS = 'GET_ADDITIONNAL_INFOS_SUCCESS';
export const GET_ADDITIONNAL_INFOS_ERROR = 'GET_ADDITIONNAL_INFOS_ERROR';