export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const INCREMENT_COUNTER_BY_NUMBER = 'INCREMENT_COUNTER_BY_NUMBER';
export const DECREMENT_COUNTER_BY_NUMBER = 'DECREMENT_COUNTER_BY_NUMBER';
